name: Publish to NPM upon new releases

on: 
  release:
    types: [created]
    branches: 
      - master

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}